#!/bin/bash
# EXECUTION CHECKLIST: Timetable System Migration

# This file shows you exactly what to do, line by line
# Copy-paste each section into your terminal

echo "========================================"
echo "TIMETABLE SYSTEM MIGRATION CHECKLIST"
echo "========================================"
echo ""

# STEP 1: Navigate to backend
echo "STEP 1: Navigate to backend directory"
echo "Command:"
echo "  cd backend"
echo ""
echo "Expected: You're now in the backend folder"
echo "Press Enter after executing..."
echo ""

# STEP 2: Run migration
echo "STEP 2: Create database tables"
echo "Command:"
echo "  node runMigration008.js"
echo ""
echo "Expected Output:"
echo "  ✅ Migration 008 completed successfully!"
echo "  📊 Tables created:"
echo "     - period_config"
echo "     - year_break_timings"
echo "     - timetable_master"
echo "     - timetable_details"
echo "     - faculty_leave_schedules"
echo "     - timetable_staff_alterations"
echo ""
echo "⚠️  If you see an error with 'Connection refused', make sure MySQL is running!"
echo "Press Enter after executing..."
echo ""

# STEP 3: Verify
echo "STEP 3: Verify all tables were created"
echo "Command:"
echo "  node verifyDatabase.js"
echo ""
echo "Expected Output:"
echo "  ✅ period_config"
echo "  ✅ year_break_timings"
echo "  ✅ timetable_master"
echo "  ✅ timetable_details"
echo "  ✅ faculty_leave_schedules"
echo "  ✅ timetable_staff_alterations"
echo ""
echo "⚠️  All 6 should have ✅ marks"
echo "Press Enter after executing..."
echo ""

# STEP 4: Restart server
echo "STEP 4: Restart backend server"
echo "If server is running, press Ctrl+C first to stop it"
echo ""
echo "Command:"
echo "  npm start"
echo ""
echo "Expected Output:"
echo "  [Server logs...]"
echo "  Server running on port 5000"
echo ""
echo "⚠️  Wait until you see 'Server running on port 5000'"
echo "Don't close this terminal!"
echo "Press Enter after executing..."
echo ""

# STEP 5: Test in browser (NEW TERMINAL)
echo "STEP 5: Test in browser (OPEN NEW TERMINAL/TAB)"
echo "Open a new terminal/tab and navigate to:"
echo "  http://localhost:3000/admin/superadmin/timetable"
echo ""
echo "Expected Result:"
echo "  ❌ NOT THIS: 500 Internal Server Error"
echo "  ✅ YES THIS: Timetable Management Dashboard loads"
echo ""
echo "You should see:"
echo "  - Dashboard header"
echo "  - Create Timetable button"
echo "  - Bulk Upload option"
echo "  - Empty timetable list"
echo ""
echo "⚠️  If you still see 500 error, check browser console (F12)"
echo "    - Clear cache: Ctrl+Shift+Delete"
echo "    - Reload: Ctrl+F5"
echo ""

# OPTIONAL: Create sample data
echo "STEP 6: (OPTIONAL) Create a sample timetable"
echo "In the browser at http://localhost:3000/admin/superadmin/timetable:"
echo "  1. Click 'Create Timetable' button"
echo "  2. Fill in:"
echo "     - Academic Year: 2024-2025"
echo "     - Semester: 1"
echo "     - Department: Select one"
echo "     - Year: 1st"
echo "  3. Click 'Create' button"
echo ""
echo "Expected:"
echo "  ✅ Timetable created successfully"
echo "  ✅ Can see it in the list above"
echo ""

echo "========================================"
echo "✅ MIGRATION COMPLETE!"
echo "========================================"
